### ISSUE TITLE
GSBUtils and IPv6

### ISSUE THREAD

**Issue by Karm** [whalebone/sinkit-core#83]
[public static String longToIPv4(long ip)](https://github.com/whalebone/sinkit-core/blob/master/ejb/src/main/java/biz/karms/sinkit/ejb/gsb/util/GSBUtils.java#L184) is missing its IPv6 sister. Furthermore, take a look at [CIDRUtils](https://github.com/whalebone/sinkit-core/blob/master/ejb/src/main/java/biz/karms/sinkit/ejb/util/CIDRUtils.java) and consider a common library for these things.

WDYT?

**Comment by kozeltom** [comment]
Yep you're right we cannot parse long (BigInteger respectively) to ipv6. Is it problem for now? Will you do lookup for ipv6 represented as BigInteger? I don't even think we do this for ipv4 now. The method is here because I wanted the tests to pass all testing data provided by Google.

**Comment by Karm** [comment]
Well, the DNS API works with IPv6, IoC can have an IPv6 address. That's why I use 40 characters - right padded String representation of BigInteger for subnets lookups.
  
Is your code IPv6 compliant? If it ain't, it should be -- later the changes are done the more painful they tend to be...

**Comment by kozeltom** [comment]
I don't understand you. Do you need to perform GSB lookup for IPv6 represented as decimal string? I don't think so. Standard hexadecimal representation (including colons) of IPv6 is not a problem.
Don't understand your note about subnets. You cannot do lookup of CIDR, just IP is allowed. CIDR cannot be on blacklist, it makes no sense, only concrete IPs are blacklisted. All in one: lookup of aabb:ccdd:eeff:0011:2233:4455:6677:8899 will work. Lookup of 340282366920938000000000000000000000000 (which is decimal representation of IPv6) won't.
One more thing: imagine a situation when you pass number 1367023452. Is it IPv4 81.123.31.92 or IPv6 0:0:0:0:0:0:517B:1F5C? As you can see it's ambiguous. So that's the reason why only IPv4 can be passed as decimal and IPv6 not.

**Comment by kozeltom** [comment]
@Karm Can we close this?

**Comment by Karm** [comment]
Not pertinent anymore.
